# Define Base IOM Colors ------------------------------------------------------
iomcolors <- list(
  blue = "#0033A0",
  white = "#FFFFFF",
  black = "#000000",
  yellow = "#FFB81C",
  grey = "#666666",
  navy = "#18375F",
  green = "#5CB8B2",
  red = "#D22630",
  orange = "#FF671F",
  lightblue = "#418FDE"
)


# Write color_variables.css ------------------------------------------

css_colors <- paste0("  --iom-", names(iomcolors), ": ", unname(unlist(iomcolors)), ";")

warning <-
"/*! This file is autogenerated in data-raw/gen_iom_colors.R. Do not manually edit */
/*! =========================================================
@name             color_variables.css
@description      IOM color variables
============================================================= */
"

fileConn <- file("inst/resources/css/color_variables.css")
writeLines(c(warning, ":root {", css_colors, "}"), fileConn)
close(fileConn)


# Generate SASS variables -------------------------------------------------

scss_colors <- paste0("$iom-", names(iomcolors), ": ", unname(unlist(iomcolors)), ";")

warning <- "// This file is autogenerated in data-raw/gen_iom_colors.R.
// Do not manually edit "


fileConn <- file("inst/resources/scss/_iomcolors.scss")
writeLines(c(warning, scss_colors), fileConn)
close(fileConn)
